spring.application.name=ExpensesTracker
spring.thymeleaf.cache=false
spring.mvc.hiddenmethod.filter.enabled=true
server.error.whitelabel.enabled=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3305/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Test@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
